### ISSUE TITLE
errors.full_messages busted

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#143]
try it and see!

Work around is to apply these two patches:

```ruby
module ReactiveRecord
  class Base
    def errors
      @errors ||= ActiveModel::Errors.new(ar_instance)
    end
  end
end

module ActiveRecord
  module ClassMethods
     def human_attribute_name(attribute, opts = {})
      opts[:default] || attribute
    end
  end
end
```

**Comment by barriehadfield** [comment]
@catmando thank you, the patch works perfectly

**Comment by barriehadfield** [comment]
Additional small bug to be aware of here:

The code below in a failing promise block:

```
error_messages = []
esult[:models].each do |response_model|
    error_messages.concat response_model.errors.full_messages
    puts "got errors: #{response_model.errors.full_messages}"
end
mutate @error_messages = error_messages
```

Problem is that the resolved errors will still be returned, so `response_model.errors.full_messages` does not clear itself of previous errors, so you get:

` got errors: First name can't be blank,Last name can't be blank,Last name can't be blank,Last name can't be blank,Last name can't be blank` even when `first_name` is supplied and you have tried a few times.

Expected behaviour is that only the current errors are returned.

**Comment by catmando** [comment]
@barriehadfield can you pull from edge and make sure everything is fixed now?
